//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rasheed_Traders
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int id { get; set; }
        public string Item { get; set; }
        public string Type { get; set; }
        public double SubTotal { get; set; }
        public int Total { get; set; }
        public string Discount { get; set; }
    }
}
