//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rasheed_Traders
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int id { get; set; }
        public string Item { get; set; }
        public string Type { get; set; }
        public string TotalDiscount { get; set; }
        public string SaleId { get; set; }
        public string Name { get; set; }
        public string SaleType { get; set; }
        public string Bonus { get; set; }
        public string OverallTotal { get; set; }
        public string Date { get; set; }
        public string Quantity { get; set; }
        public string Discount { get; set; }
        public string SubTotal { get; set; }
        public string R_Price { get; set; }
        public string Total { get; set; }
        public string Location { get; set; }
    }
}
